server:
  port: 9080
spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/testdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

logging.level.org.jooq: trace
logging.level.org.springframework.security: TRACE
