server:
  port: 9080
spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/testdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

## https://docs.spring.io/spring-boot/docs/3.0.1/reference/htmlsingle/#features.logging.log-levels
# パラメータの値をログに表示
# 2023-01-21T20:27:23.263+09:00 TRACE 8212 --- [nio-9080-exec-1] org.hibernate.orm.jdbc.bind              : binding parameter [1] as [VARCHAR] - [admin]
# logging.level.org.hibernate.type: trace にして出力されるログからパッケージを特定
logging.level.org.hibernate.orm.jdbc.bind : trace

#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE