server:
  port: 9080
spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/testdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password

logging.level.org.jooq: trace
logging.level.org.springframework.security: TRACE
